stages:
  - test
  - -package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

test:
  stage: test
  image: eclipse-temurin:25
  script:
    - chmod +x mvnw
    - ./mvnw test

package:
  stage: package
  image: eclipse-temurin:25
  script:
    - chmod +x mvnw
    - ./mvnw clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week